language: python
python:
  # - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  #  if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #   else
  #     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   fi
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - source "$HOME/miniconda/etc/profile.d/conda.sh"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # # Useful for debugging any issues with conda
  # - conda info -a
  # - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  # - conda activate test-environment
  # - python setup.py install
# command to run tests
script:
  - pytest deck
